name: Docker

on:
  push:
    branches:
      - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      infrastruktur_changed: ${{ steps.filter.outputs.infrastruktur_changed }}
      nutzung_changed: ${{ steps.filter.outputs.nutzung_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infrastruktur_changed:
              - 'apps/Infrastruktur/**'
            nutzung_changed:
              - 'apps/Nutzung/**'

  build_and_push_docker_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.infrastruktur_changed == 'true' || needs.paths-filter.outputs.nutzung_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Infrastruktur Image
        if: needs.paths-filter.outputs.infrastruktur_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/laden-leicht-gemacht:infrastruktur-latest
          platforms: windows/amd64
          target: infrastruktur

      - name: Build and Push Nutzung Image
        if: needs.paths-filter.outputs.nutzung_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/laden-leicht-gemacht:nutzung-latest
          platforms: linux/arm64
          target: nutzung
